#!/bin/bash

################################################################################
# Script to build the web directory ready for deployment.
#
# ! Do not change this file !
# All configuration is in the config directory
################################################################################


# Bootstrap the script.
source $(dirname $0)/src/bootstrap.sh

# Includes.
source "$DIR_SRC/script.sh"
source "$DIR_SRC/build.sh"
source "$DIR_SRC/drupal_composer.sh"

# Pre script.
build_info
prompt_confirm_or_exit

# START Script -----------------------------------------------------------------
script_before_run
build_check_directory
build_drupal_composer
build_package_run
script_after_run
# END Script -------------------------------------------------------------------

# Finish message.
build_finished

# End.
exit 0
