#!/bin/bash

################################################################################
# Script that acts as a wrapper around the drush cli tool.
#
# The wrapper will always execute drush within the web directory.
#
# ! Do not change this file !
# All configuration is in the config directory
################################################################################


# Bootstrap the script.
source $(dirname $0)/src/bootstrap.sh

# START Script -----------------------------------------------------------------

markup_debug
markup_debug "Start : $(date '+%Y-%m-%d %H:%M:%S')"
markup_debug

# Create the global $DRUSH_OPTIONS array.
drupal_drush_filter_options

drupal_drush "${DRUSH_OPTIONS[@]}"

markup_debug
markup_debug "Drush binary used : $DRUSH_VERSION"
markup_debug "Drush params : $drush_params"

markup "${GREY}Finished : $(date '+%Y-%m-%d %H:%M:%S')"
echo

# END Script -------------------------------------------------------------------

# End.
exit 0
