#!/bin/bash

################################################################################
# Script to reset the environment by deleting the DB & Files directory and
# reinstall Drupal.
#
# ! Do not change this file !
# All configuration is in the config directory
################################################################################


# Bootstrap the script.
source $(dirname $0)/src/bootstrap.sh

# Includes.
source "$DIR_SRC/script.sh"
source "$DIR_SRC/reset.sh"
source "$DIR_SRC/backup.sh"
source "$DIR_SRC/cleanup.sh"
source "$DIR_SRC/drupal_install.sh"
source "$DIR_SRC/drupal_modules_disable.sh"
source "$DIR_SRC/drupal_modules_enable.sh"
source "$DIR_SRC/drupal_login.sh"

# Pre script.
reset_init
reset_info
prompt_confirm_or_exit

# START Script -----------------------------------------------------------------
script_before_run
backup_run
cleanup_run
drupal_install_run
drupal_modules_disable_run
drupal_modules_enable_run
drupal_login_run
script_after_run
# END Script -------------------------------------------------------------------

# Finish message.
reset_finished

End.
exit 0
