#!/bin/bash

################################################################################
# Script to upgrade an existing site based on the configuration by replacing
# core & contrib by removing the web directory and download again based on the
# composer files.
#
# ! Do not change this file !
# All configuration is in the config directory
################################################################################


# Bootstrap the script.
source $(dirname $0)/src/bootstrap.sh

# Includes.
source "$DIR_SRC/script.sh"
source "$DIR_SRC/upgrade.sh"
source "$DIR_SRC/backup.sh"
source "$DIR_SRC/cleanup.sh"
source "$DIR_SRC/drupal_composer.sh"
source "$DIR_SRC/restore.sh"
source "$DIR_SRC/drupal_upgrade.sh"
source "$DIR_SRC/drupal_login.sh"

# Pre script.
upgrade_init
upgrade_info
prompt_confirm_or_exit

# START Script -----------------------------------------------------------------
script_before_run
backup_run
backup_run_sites_default_directory
cleanup_run
drupal_composer_run
restore_run_sites_default_directory
drupal_upgrade_run
drupal_login_run
script_after_run
# END Script -------------------------------------------------------------------

# Finish message.
upgrade_finished

# End.
exit 0
